# -*- coding: utf-8 -*-
"""ATV_3_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vSlVryJXkXOi6JTUG67ZmRs-RlGfkfI

## Nome: Pedro Henrique Ribeiro Dias
## Matrícula: 529

---

PARTE PRÁTICA

# Atividade – Análise de Erros em Medições Experimentais

Questão 1.

Um professor de Engenharia Química, realizou um experimento com seus alunos
à respeito do calor específico da água. O experimento consiste em aquecer uma
massa de água com um calorímetro e com isso medir a variação da temperatura, assim podendo calcular os
novos valores do calor específico. Porém, os resultados obtidos foram diferentes do
valor exato do calor específico da água. Devido à isso o professor
passou esses dados em uma tabela para você fazer um estudo sobre erros e métodos numéricos.

Importante citar que o valor do calor específico da água é de aproximadamente 4,186 kJ/(kg·K)


Os resultados dos alunos estão na tabela abaixo:

| Alunos               | Valor Medido (KJ) |
|-----------------------------------|---------------------|
| Karina             | 4.18           |
| Pedro        | 4.17               |
| Lívia               |     4.178           |
| Lucas      | 4.189               |
| Paulo            | 4.201             |
| Soned       | 4.187             |


Seu objetivo é analisar esses dados e calcular diferentes métricas de erro,
utilizando Python e bibliotecas como **pandas**, **numpy** e **matplotlib**.

---
"""

from IPython.display import display, Markdown
# Importando bibliotecas

#Analise de dados
import pandas as pd
import numpy as np

#Plotar gráficos
import matplotlib.pyplot as plt

#Tabela de dados
tabela = {
    "Alunos": [
        "Karina", "Pedro", "Livia",
        "Lucas", "Paulo",
        "Soned"
    ],
    "Valor Medido (K*J)": [4.18, 4.17, 4.178, 4.189, 4.201, 4.187]
}

dados = pd.DataFrame(tabela)
display(dados)

"""### Parte 1 - Erro Absoluto, Erro Relativo e Erro Percentual"""

# Ordenando igual a atividade passada
df_ordenado = dados.sort_values(by='Valor Medido (K*J)', ascending=True).reset_index(drop=True)

# Valor teórico
valor_teorico = 4.186

# Funções para calcular os erros
def erroAbsoluto(vt, vm):
    return abs(vt - vm)

def erroRelativo(vt, vm):
    ea = erroAbsoluto(vt, vm)
    return ea / abs(vm)

def erroPercentual(vt, vm):
    er = erroRelativo(vt, vm)
    return er * 100

# Calcular e imprimir os resultados
for i in range(len(df_ordenado)):
    aluno = df_ordenado["Alunos"][i]
    vm = df_ordenado["Valor Medido (K*J)"][i]
    ea = erroAbsoluto(valor_teorico, vm)
    er = erroRelativo(valor_teorico, vm)
    ep = erroPercentual(valor_teorico, vm)

    print(f"Aluno: {aluno}")
    print(f"Valor Medido: {vm}")
    print(f"Erro Absoluto: {ea}")
    print(f"Erro Relativo: {er}")
    print(f"Erro Percentual: {ep}%")
    print("-" * 30)

"""Calcule o Erro Absoluto, o Erro Relativo e o Erro Percentual dos valores medidos.

**Formulário para cálculo de erros do calor específico**

- Erro Absoluto:  
$$E_a = |V_t - V_m|$$

- Erro Relativo:  
$$E_r = \frac{E_a}{|V_m|}$$

- Erro Percentual:  
$$E_p = E_r \times 100\%$$

Onde:  
- $V_t$ = valor teórico do calor específico (4,186 kJ/(kg·K))  
- $V_m$ = valor medido pelo aluno

### Parte 2 - Arredondamento e Truncamento

Um engenheiro de produção está desenvolvendo um sistema para controle de corte de peças metálicas.
O equipamento mede o comprimento das peças, mas as medições apresentam várias casas decimais,
sendo necessário arredondar os valores para atender às especificações técnicas da indústria.
Esse engenheiro, a fim de deixar mais didático as suas medições, decidiu propor para você uma série de tarefas,
e você deverá auxiliá-lo nessa importante atividade.

As medidas coletadas pelo engenheiro estão anotadas na tabela:

| Peça              | Comprimento medido (cm) |
|-----------------------------------|---------------------|
| P1             | 12.3456           |
| P2        |           9.8765     |
| P3               |     15.5555          |
| P4      | 7.4999            |
| P5            | 10.0501            |

As terefas pedidas por eles são:

### 1 - Fazer um DataFrame para organização visual dos dados
"""

#Tabela de dados
tabela = {
    "Peças": [
        "P1", "P2", "P3",
        "P4", "P5"
    ],
    "Comprimento Medido (cm)": [12.3456, 9.8765, 15.5555, 7.4999, 10.0501]
}

dados = pd.DataFrame(tabela)
display(dados)

"""### 2 - Preciso que arredonde todos os valores para 2 casas decimais, para me ajudar nos cálculos"""

dados["Arredondado (2 casas)"] = dados["Comprimento Medido (cm)"].round(2)

"""### 3 - Após isso, quero que trunque os valores para 1 casa decimal"""

dados["Truncado (1 casa)"] = np.trunc(dados["Comprimento Medido (cm)"] * 10) / 10

"""### 4 - Mostre para mim depois, o valor inteiro mais próximo"""

dados["Inteiro mais próximo"] = dados["Comprimento Medido (cm)"].round(0).astype(int)

"""### 5 - E me mostrar os resultados dentro de uma tabela"""

display(dados)

"""<span style="font-size:90%">

**Guia Rápido: Arredondamento e Truncamento**

- Arredondar para n casas decimais: `dados["Comprimento Medido (cm)"].round(0)`  
- Truncar para n casas decimais: `np.trunc(dados["Comprimento Medido (cm)"] * 10) / 10`  
- Arredondar para inteiro mais próximo: `dados["Comprimento Medido (cm)"].round(0).astype(int)`

</span>

## Parte Teórica

**Questão 1.**

Julgue as afirmativas abaixo como V (Verdadeiro) ou F (Falso) e justifique as que forem Falsas.

1. É possível representar qualquer grandeza física em termos das unidades básicas da Física. ( )

2. O instrumento de medida escolhido para medir uma grandeza deve ser coerente com aquilo que se deseja medir. ( )

3. A incerteza não precisa ser levada em consideração e não é necessária para compararmos os dados. ()

4. O erro relativo é calculado dividindo o erro absoluto pelo valor teórico. ()

5. O número de algoritmos significativos de uma grandeza é determinado pela sua incerteza. ()

**Questão 2.**

Quando você faz a medição de alguma grandeza, com um instrumento de medição qualquer, em qual conjunto cai a medida que você
obteve?

Conjunto dos números Naturais, Inteiros, Racionais, Irracionais, Reais ou Complexos? Justifique sua resposta

**Questão 3.**

Suponhamos que deseje medir o tamanho de um besouro.
Foi decidido também, o que caracteriza o tamanho do besouro, qual das alternativas abaixo melhor caracteriza a medida
do tamanho do besouro?

a) Entre 0 e 1 cm

b) Entre 1 e 2 cm

c) Entre 1,5 e 1,6

d) Entre 1,54 e 1,56

e) Entre 1,546 e 1,547

![image.png](attachment:image.png)

**Questão 4.**


Seja o número a = 4876 representado por a
′ = 4875,8 e seja o número 𝑦 = 12,7 representado por
𝑦
′ = 12,6.

Pode-se dizer que ambos os números estão representados com a mesma precisão?

**Respostas:**

Questão 1:
1. V
2. V
3. F
4. V
5. V

Questão 2:
O valor obtido pela medição estára dentro do conjunto dos números racionais, pois ao medir usando algum equipamento o resultado será um decimal com casas decimais finitas.

Questão 3:
D

Questão 4:
Não, não têm a mesma precisão. Embora ambos estejam com uma casa decimal, a representação de a é muito mais precisa do que a de y. Podemos observar isso ao calcular o erro relativo de cada um, em que a tem ER da ordem de 10^-5 porém y da ordem de 10^-3.
"""