# -*- coding: utf-8 -*-
"""ATV_12_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Szr_3bug2cTjxDnYoZ1P-xGPpDTP0XW

## Nome: Pedro Henrique Ribeiro Dias
## Matricula: 529
-----

# ATIVIDADE 12 - Tabela de frequências e gráficos para variáveis qualitativas.

**Objetivo:** Reforçar a construção de tabelas de frequência absoluta, relativa e acumulada.

---

Uma pesquisa foi feita com 50 estudantes sobre o principal meio de transporte usado para ir até a escola. As respostas obtidas foram:

| Meio de transporte | Quantidade de estudantes |
| ------------------ | ------------------------ |
| Carro              | 12                       |
| Ônibus             | 20                       |
| Bicicleta          | 8                        |
| A pé               | 10                       |

Questão 1 - Monte uma tabela de frequências (Frequência Relativa e Frequência Acumulada)
"""

import pandas as pd

# Utilize o DataFrame
import pandas as pd

dadosTabela = {'Meio de transporte': ['Carro', 'Ônibus', 'Bicicleta', 'A pé'],
         'Quantidade': [12, 20, 8, 10]}

df = pd.DataFrame(dadosTabela)

# Total de estudantes
total = df['Quantidade'].sum()

# Frequência relativa e acumulada
df['Frequência Relativa'] = (df['Quantidade'] / total) * 100
df['Frequência Acumulada'] = df['Frequência Relativa'].cumsum()

# Printando toda a tabela
df

"""Questão 2 - Crie um gráfico de barras"""

import matplotlib.pyplot as plt

plt.bar(df['Meio de transporte'], df['Quantidade'], color='skyblue')
plt.title('Meio de Transporte - Frequência Absoluta')
plt.xlabel('Meio de Transporte')
plt.ylabel('Quantidade de Estudantes')
plt.show()

"""Questão 3 - Crie um gráfico de pizza"""

plt.pie(df['Quantidade'], labels=df['Meio de transporte'], autopct='%1.1f%%')
plt.title('Distribuição dos Meios de Transporte')
plt.show()

"""Questão 4 - Interprete os resultados
- Qual meio de transporte é mais utilizado?
- Qual meio de transporte é menos utilizado?
- Qual é a diferença percentual entre o mais e o menos frequente?
"""

print(f"O meio de transporte mais utilizado é: {df.loc[df['Quantidade'].idxmax(), 'Meio de transporte']}")
print(f"O meio de transporte menos utilizado é: {df.loc[df['Quantidade'].idxmin(), 'Meio de transporte']}")
print(f"A diferença percentual entre o mais e o menos frequente é: {df['Frequência Relativa'].max() - df['Frequência Relativa'].min():.1f}%")