# -*- coding: utf-8 -*-
"""ATV10_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNU7bcZJ6orIKwm3BEim1un6L3mlMOTA

## Nome: Pedro Henrique Ribeiro Dias
## Mátricula: 529
---

# Atividade 10 – Integração Numérica


## Objetivo da Atividade
Compreender e aplicar o **Método dos Trapézios** para aproximar o valor de uma integral definida de uma função contínua em um intervalo [a, b].

Você deverá:
- Implementar a **regra do trapézio simples** e a **regra dos trapézios composta**.
- Comparar os resultados obtidos com o valor analítico da integral.
---

## Contexto

Em muitos casos, **a primitiva F(x)** de uma função não é conhecida ou é difícil de obter.  
Além disso, nem sempre a função está definida por uma expressão analítica — às vezes temos apenas **valores tabelados** (dados experimentais).

Nessas situações, recorremos aos **métodos numéricos de integração**, que permitem **estimar a área sob uma curva** de forma aproximada.

---

## Método dos Trapézios

A ideia central do **Método dos Trapézios** é substituir a função integrando **f(x)** por um **polinômio interpolador de grau 1** (ou seja, uma **reta**) que passe pelos extremos do intervalo \([a, b]\).

---

## Problema Proposto

Vamos calcular numericamente o valor aproximado da integral:

$$
I = \int_{0}^{1} e^x \, dx
$$

usando dois métodos:

1. **Regra dos Trapézios** — com **1 intervalo**  
2. **Regra dos Trapézios Repetida** — com **4 subintervalos**

O valor exato da integral é conhecido e será usado para comparação:

$$
I_{exato} = e - 1 \approx 1.718282
$$

----

Abaixo, temos as bibliotecas necessárias para a execução do método!


A função que iremos trabalhar e o intervalo de integração!
"""

import numpy as np
import matplotlib.pyplot as plt

#Funcao a ser integrada
def funcao(x):
    return np.exp(x)

#Intervalo de Integracao
a = 0
b = 1

"""-----

## Como resolver utilizando o Método dos Trapézios (1 intervalo)

**Passo 1:** Calcular h:
$$
h = b - a
$$

**Passo 2:** Calcular \(f(x0)\) e \(f(x1)\):
$$
fx0 = f(0)               
;
fx1 = f(1)
$$
**Passo 3:** Aplicar a fórmula:
$$
(h / 2) * (f(x0) + f(x1))      
$$

**Passo 4:** Comparar o valor obtido com o valor exato

**Passo 5:** Mostrar resultados

**Passo 6:** Gerar um gráfico que mostre a função:
$$
f(x) = e^x
$$
no intervalo [0, 1] e o trapézio formado entre os pontos a e b

# Resolva aqui, de forma organizada, os passos que foram mencionados acima acerca do método dos Trapézios com 1 intervalo:
"""

# Trapézio Simples (1 intervalo)

# Passo 1 - Calcular h
def alt(a, b):
  return b-a

h = alt(a, b)

# Passo 2 - Calcular f(x0) e f(x1)
def fx(x0, x1):
  return funcao(x0), funcao(x1)

fx0, fx1 = fx(a,b)

# Passo 3 - Aplicar a fórmula do trapézio
def trap(fx0, fx1, h):
  return (h/2) * (fx0 + fx1)

IT = trap(fx0, fx1, h)

# Passo 4 - Comparar com valor exato
I_exato = np.e - 1
erro = abs(IT - I_exato)

# Passo 5 - Mostrar resultados
print(f'O valor aproximado da integral é: {IT}')
print(f"A integral exata é: {I_exato}")
print(f"O erro é: {erro}")

#Passo 6
#plt.plot() e plt.fill_between() para desenhar a curva e preencher a area do trapezio

x = np.linspace(a, b, 100)
y = funcao(x)
plt.plot(x, y, 'b', label='f(x) = e^x')
plt.fill_between([a, b], [funcao(a), funcao(b)], color='orange', alpha=0.3, label='Área (trapézio simples)')
plt.show()

"""---

##  Como resolver utilizando o Método dos Trapézios (4 subintervalos)

**Passo 1:** Definir o número de subintervalos  
\( n = 4 \)

**Passo 2:** Calcular \(h\)

$$
h = \frac{b - a}{n}
$$

**Passo 3:** Obter os intervalos de integração

$$
 \quad (xi = 0, 0,25, 0,5, 0,75, 1)
$$

**Passo 4:** Calculos os pontos -> (f(x0), f(x1), f(x2), f(x3), f(x4))
$$
f(xi) = e^xi
$$

**Passo 5:** Aplicar a Regra dos Trapézios Repetida

$$
I_T = \frac{h}{2} [f(x_0) + 2(f(x_1) + f(x_2) + f(x_3)) + f(x_4)]
$$

**Passo 6:** Comparar o valor obtido com o valor exato

$$
I_{exato} = e - 1 \approx 1{,}718282
$$

**Passo 7:** Mostrar resultados

**Passo 8:** Gerar um gráfico mostrando a curva
$$
f(x) = e^x
$$
 e os 4 trapézios utilizados na aproximação composta da integral.

# Resolva aqui, de forma organizada, os passos que foram mencionados acima acerca do método dos Trapézios com 4 intervalos:
"""

# Trapézios Repetidos (4 subintervalos)

# Passo 1 - Definir número de subintervalos
n = 4

# Passo 2 - Calcular h
h = alt(a, b)/n

# Passo 3 - Obter os pontos xi de integracao
xi = np.linspace(a, b, n+1)

# Passo 4 - Calculando os valores f(x0), f(x1), f(x2), f(x3), f(x4) para aplicarmos na fórmula
fxi = []

for i in (xi):
  fxi.append(funcao(i))

# Passo 5 - Aplicar a Regra dos Trapézios Repetida

It = (h/2) * (fxi[0] + 2*(fxi[1] + fxi[2] + fxi[3]) + fxi[4])

# Passo 6 - Comparar com o valor exato
I_exato = np.e - 1
erro = abs(It - I_exato)

# Passo 7 - Mostrar resultados
print(f"O valor aproximado da integral é: {It}")
print(f"A integral exata é: {I_exato}")
print(f"O erro é: {erro}")

#Passo 8
x = np.linspace(a, b, 100)
y = funcao(x)
plt.plot(x, y, 'b', label='f(x) = e^x')

for i in range(n):
    xs = [xi[i], xi[i+1]]
    ys = [funcao(xi[i]), funcao(xi[i+1])]
    plt.fill_between(xs, ys, color='orange', alpha=0.3)

plt.show()