# -*- coding: utf-8 -*-
"""ATV8_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xg1aSNBL8XAidM9snDRO0135mIqHHjhM

## Nome: Pedro Henrique Ribeiro Dias
## Mátricula: 529
---

# Atividade – Ajuste Polinomial


## Objetivo da Atividade
Nesta atividade, você irá aplicar o ajuste polinomial para resolver um problema inspirado em projetos da FETIN – Feira Tecnológica do Inatel, explorando o método dos mínimos quadrados.

## Contexto
Durante a FETIN, alunos de engenharia apresentam protótipos de sistemas inovadores.

Imagine um grupo que desenvolveu um sistema de iluminação inteligente para otimizar o consumo de energia em um prédio do campus.

Eles coletaram dados experimentais que relacionam:
- Número de pessoas em uma sala (x)
- Consumo médio de energia em kWh (y)

Tabela obtida nos testes:

| Pessoas (x) | 1  | 2  | 3  | 4  | 5  | 6  |
|-------------|----|----|----|----|----|----|
| Consumo (y) | 2.1| 3.0| 4.5| 6.8| 9.5| 12.0|
"""

import numpy as np
import matplotlib.pyplot as plt

"""## Funções de Apoio"""

# Função para ajuste polinomial
def ajuste_polinomial(x, y, grau):
    coef = np.polyfit(x, y, grau)
    p = np.poly1d(coef)
    return p

# Função para plotar o ajuste
def plot_ajuste(x, y, p, titulo="Ajuste Polinomial"):
    xp = np.linspace(min(x), max(x), 100)
    plt.scatter(x, y, color="red", label="Dados experimentais")
    plt.plot(xp, p(xp), color="blue", label=f"Ajuste (grau {p.order})")
    plt.title(titulo)
    plt.xlabel("Número de pessoas")
    plt.ylabel("Consumo (kWh)")
    plt.legend()
    plt.grid(True)
    plt.show()

x = np.array([1,2,3,4,5,6])
y = np.array([2.1,3.0,4.5,6.8,9.5,12.0])

"""## Questão 1 – Visualização inicial
1. Plote o gráfico de dispersão dos pontos experimentais.

"""

plt.scatter(x, y, color="red")
plt.title("Gráfico de Dispersão")
plt.xlabel("Número de pessoas")
plt.ylabel("Consumo (kWh)")
plt.grid(True)
plt.show()

"""2. Pelo gráfico, qual grau de polinômio parece se ajustar melhor aos dados? (1º, 2º ou 3º grau?)

**RESPOSTA:** Um polinômio de 2º grau se ajusta melhor do que os demais.

## Questão 2 – Ajuste Linear (1º grau)
1. Calcule o polinômio de ajuste de grau 1.
"""

p1 = ajuste_polinomial(x, y, 1)
print(p1)

"""2. Escreva a função ajustada no formato $p(x) = a_0 + a_1x$.

"""

print(f"p(x) = −0.6 + 2.04x")

"""3. Plote o gráfico do ajuste junto com os pontos experimentais."""

plot_ajuste(x, y, p1, titulo="Ajuste Linear (1º grau)")

"""## Questão 3 – Ajuste Quadrático (2º grau)
1. Calcule o polinômio de ajuste de grau 2.


"""

p2 = ajuste_polinomial(x, y, 2)
print(f"Polinômio de 2º grau: {p2}")

"""2. Escreva a função ajustada."""

print(f"Função ajustada: p(x) = {p2.coefficients[0]:.3f}x² + {p2.coefficients[1]:.3f}x + {p2.coefficients[2]:.3f}")

"""3. Compare o gráfico do polinômio de 2º grau com o do 1º grau.

"""

# Comparação
plot_ajuste(x, y, p1, titulo="Comparação Ajuste Linear")
plot_ajuste(x, y, p2, titulo="Comparação Ajuste Quadrático")

"""4. Qual deles melhor representa os dados?

**RESPOSTA:**

## Questão 4 – Teste de Previsão
1. Usando o polinômio ajustado, estime o consumo de energia para 8 pessoas na sala.
"""

y_prev = p2(8)
print(f"Consumo estimado para 8 pessoas = {y_prev:.2f} kWh")

"""2. Essa previsão parece realista? Justifique.

**RESPOSTA:** A previsão é parcialmente realista, pois estamos extrapolando o conjunto de dados dados, então estaremos assumindo que a função terá  o mesmo comportamento em seguida.
"""