# -*- coding: utf-8 -*-
"""ATV_14_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9ycKHZcDET_jPh9ngc0epQ1f6aAOKMH

## Nome: Pedro Henrique RIbeiro Dias
## Matricula:529
-----

# **ATV — Testes Categorizados**

Esta atividade pratica os **testes para dados categorizados**: Qui‑quadrado clássico, Qui‑quadrado com correção de Yates, Teste Exato de Fisher e Teste de McNemar.

**Objetivos**
- Montar tabelas de contingência e formular hipóteses (H0/H1).
- Calcular valores **esperados** e a estatística **χ²** (ou **p‑valor**), decidir e concluir.
- Usar `scipy.stats`/`statsmodels` para conferir os cálculos.
- Interpretar resultados nos níveis usuais de significância (1%, 5%, 10%).

## Instruções gerais

- Execute as células na ordem em que aparecem.
- Sempre **declare as hipóteses** antes de calcular (H0 = igualdade; H1 = diferença).
- Para tabelas 2×2, você pode usar:
  - `stats.chi2_contingency(obs, correction=False)` → χ² clássico;
  - `stats.chi2_contingency(obs, correction=True)` → com **Yates**;
  - `stats.fisher_exact(obs, alternative="two-sided")` → **Fisher** (n pequeno ou valores esperados < 5);
  - `mcnemar(tabela_pareada, exact=True/False, correction=True/False)` → **McNemar** (amostras pareadas).
"""

# Imports úteis para toda a atividade
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.contingency_tables import mcnemar

pd.set_option("display.precision", 4)

"""
## Funções auxiliares
"""

def esperados_from_obs(obs):
    obs = np.asarray(obs, dtype=float)
    row_sum = obs.sum(axis=1, keepdims=True)
    col_sum = obs.sum(axis=0, keepdims=True)
    total = obs.sum()
    return row_sum @ col_sum / total

def decide_from_p(p, alphas=(0.10, 0.05, 0.01)):
    return {a: ("Rejeita H0" if p < a else "Não rejeita H0") for a in alphas}

"""
## Exercício 1 — Qui‑quadrado **clássico** (amostras independentes, **n > 40**)

**Contexto**: Ensaio clínico com pacientes com dor abdominal. Grupo **Tratamento** recebeu brometo de pinavério; grupo **Controle** recebeu placebo.  
Tabela de **valores observados** (2×2), **n = 154**:

|                 | **Dor Sim** | **Dor Não** | **Total** |
|-----------------|:-----------:|:-----------:|:---------:|
| **Tratamento**  |      6      |     57      |    63     |
| **Controle**    |     30      |     61      |    91     |
| **Total**       |     36      |    118      |   154     |

1. Formule H0 e H1.
2. Calcule a **tabela de esperados** e a estatística **χ² calculado** (sem correção).
3. Obtenha **gl**, **χ² tabelado** para α∈{10%,5%,1%} (use SciPy) e o **p‑valor**.
4. Decida e conclua sobre a **eficácia do tratamento**.
"""

# Tabela observada (Exemplo 1)
obs1 = np.array([[6, 57],
                 [30, 61]])
obs1_df = pd.DataFrame(obs1, index=["Tratamento","Controle"], columns=["Dor_Sim","Dor_Nao"])

print("H0 - Grupo Tratamento = Grupo Controle")
print("H1 - Grupo Tratamento != Grupo Controle")

# χ² clássico (sem correção de Yates) e esperados
chi2, p, dof, expected = stats.chi2_contingency(obs1, correction=False)
expected_df = pd.DataFrame(expected, index=obs1_df.index, columns=obs1_df.columns)

print("Tabela Esperada")
print(expected_df)

print("\nEstatística do Qui-quadrado")
print(f"χ² calculado = {chi2:.4f}")
print(f"valor de p = {p:.6f}")
print(f"gl = {dof}")

# χ² tabelado (crítico) para níveis usuais
alphas = [0.10, 0.05, 0.01]
chi2_crit = {a: stats.chi2.ppf(1 - a, dof) for a in alphas}

print("\nχ² Tabelado (valores críticos)")
print(f"α = 0.10 - χ² crítico = {chi2_crit[0.10]:.4f}")
print(f"α = 0.05 - χ² crítico = {chi2_crit[0.05]:.4f}")
print(f"α = 0.01 - χ² crítico = {chi2_crit[0.01]:.4f}")

decisoes = decide_from_p(p)
print("\nDecisão (usando p)")
print(f"α = 0.10 - {decisoes[0.10]}")
print(f"α = 0.05 - {decisoes[0.05]}")
print(f"α = 0.01 - {decisoes[0.01]}")

print(f"Assim fica comprovado o efeito do Brometo de Pinavério no tratamento. O erro envolvido é de {p:.6f}")
print("isto é, uma decisão altamente signifcativa de que a decisão é correta")

"""**Conclusão:** Assim fica comprovado o efeito do Brometo de Pinavério no tratamento. O erro envolvido é de 0.0726%, isto é, uma decisão altamente signifcativa de que a decisão é correta

## Exercício 2 — Qui‑quadrado **com correção de Yates** (amostras independentes, **20 < n < 40**)

Considere a tabela 2×2 abaixo com **n = 32** (dados fictícios para prática).

| Grupo | Sucesso | Fracasso | Total |
|-------|:-------:|:--------:|:-----:|
| A     |   14    |    2     |  16   |
| B     |    6    |   10     |  16   |
| **Total** | 20 | 12 | 32 |

1. Formule H0 e H1.
2. Calcule os **esperados** e **χ²** com **correção de Yates**.
3. Informe **gl**, **p‑valor** e **decisão** para α∈{10%,5%}.
"""

obs2 = np.array([[14, 2],
                 [ 6,10]])
obs2_df = pd.DataFrame(obs2, index=["A","B"], columns=["Sucesso","Fracasso"])

# χ² com correção de Yates
chi2_y, p_y, dof_y, exp2 = stats.chi2_contingency(obs2, correction=True)

print("H0 - Grupo Sucesso = Grupo Fracasso")
print("H1 - Grupo Sucesso != Grupo Fracasso")

print("\nEstatística com correção de Yates")
print(f"χ² calculado = {chi2_y:.4f}")
print(f"valor de p = {p:.6f}")
print(f"gl = {dof_y}")

alphas = [0.10, 0.05]
crit2 = {a: stats.chi2.ppf(1 - a, dof_y) for a in alphas}

print("\nχ² Tabelado (valores críticos)")
print(f"α = 0.10 - χ² crítico = {crit2[0.10]:.4f}")
print(f"α = 0.05 - χ² crítico = {crit2[0.05]:.4f}")

decisoes = decide_from_p(p_y)
print("\nDecisão (usando p)")
print(f"α = 0.10 - {decisoes[0.10]}")
print(f"α = 0.05 - {decisoes[0.05]}")

print("Conclusão: p < 0.05 - rejeita H0; há evidência de diferença entre os grupos.")

"""**Conclusão:**  p < 0.05 - rejeita H0; há evidência de diferença entre os grupos.

## Exercício 3 — **Teste Exato de Fisher** (amostras independentes, **n < 20** ou esperados < 5)

**Sobrevida de ratos** após 1,5 ano:

|           | **Vivos** | **Mortos** | **Total** |
|-----------|:---------:|:----------:|:---------:|
| **Normal**      |     5     |     2      |    7     |
| **Experimental**|     1     |     8      |    9     |
| **Total**       |     6     |    10      |    16    |

1. Formule H0 e H1 (duas caudas).
2. Aplique **Fisher** (two‑sided) → **p‑valor**.
3. Decida em α=5% e conclua.
"""

obs3 = np.array([[5,2],
                 [1,8]])
oddsratio, p_fisher = stats.fisher_exact(obs3, alternative="two-sided")

print("H0 - Grupo Vivos = Grupo Mortos")
print("H1 - Grupo Vivos != Grupo Mortos")

print(f"\nvalor de p = {p_fisher:.6f}")

decisoes = decide_from_p(p_fisher)
print("\nDecisão (usando p)")
print(f"α = 0.05 - {decisoes[0.05]}")

print("Conclusão: p < 0.05 - rejeita H0; há evidência de diferença nas proporções de sobrevivência entre os grupos.")
print(f"Odds ratio = {oddsratio:.1f} (maior probabilidade de sobrevivência no grupo Normal).")

"""**Conclusão:** p < 0.05 - rejeita H0; há evidência de diferença nas proporções de sobrevivência entre os grupos. Havendo maior probabilidade de sobrevivência no grupo Normal

## Exercício 4 — **Teste de McNemar** (amostras pareadas: antes × depois)

**Teste de memória (n = 40)** — número de acertos **completos** (15 palavras) antes e depois do fármaco:

Tabela **pareada** (linhas = Antes; colunas = Depois):

|             | **Correto** | **Incorreto** | **Total** |
|-------------|:-----------:|:-------------:|:---------:|
| **Correto** |      8      |       1       |     9     |
| **Incorreto** |    14     |      17       |    31     |
| **Total**   |     22      |      18       |    40     |

1. Formule H0 e H1 (duas caudas).
2. Calcule McNemar com e sem correção de Yates; reporte **estatística** e **p‑valor**.
3. Decida (α=1% e α=5%) e conclua.
"""

tab = np.array([[8,1],[14,17]])
res_corr = mcnemar(tab, exact=False, correction=True)   # com Yates
res_semc = mcnemar(tab, exact=False, correction=False)  # sem correção

print("H0 - Grupo Corretos = Grupo Incorretos")
print("H1 - Grupo Corretos != Grupo Incorretos")

print("\nMcNemar (com correção):")
print(f"Estatística = {res_corr.statistic:.6f}")
print(f"p-value    = {res_corr.pvalue:.6f}")

print("\nMcNemar (sem correção):")
print(f"Estatística = {res_semc.statistic:.6f}")
print(f"p-value    = {res_semc.pvalue:.6f}")

for a in (0.05, 0.01):
    print(f"\nDecisão (α = {a}):")
    print(f"  com correção : {'Rejeita H0' if res_corr.pvalue < a else 'Não rejeita H0'} (p = {res_corr.pvalue:.6f})")
    print(f"  sem correção  : {'Rejeita H0' if res_semc.pvalue < a else 'Não rejeita H0'} (p = {res_semc.pvalue:.6f})")

print("\nConclusão: ambos os testes (com e sem correção) têm p < 0.01, assim rejeita-se H0. Há evidência de diferença entre antes e depois.")

"""
**Conclusão:** ambos os testes (com e sem correção) têm p < 0.01, assim rejeita-se H0. Há evidência de diferença entre antes e depois."""