# -*- coding: utf-8 -*-
"""ATV_15_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfEb9XcgWFpefB6qNlaYoLTavTOJxWJA

## Nome: Pedro Henrique Ribeiro Dias
## Matricula: 529
-----

# **Atividade 15 - Testes não paramétricos**

## 1 -Teste dos Sinais (Amostras Pareadas)

Um fisioterapeuta quer saber se um novo exercício respiratório reduz a frequência respiratória dos pacientes.
Foram medidos os valores antes e depois em 8 pessoas:

| **Paciente** | **Antes** | **Depois** |
| ------------ | --------- | ---------- |
| 1            | 22        | 20         |
| 2            | 24        | 23         |
| 3            | 19        | 18         |
| 4            | 26        | 25         |
| 5            | 21        | 22         |
| 6            | 23        | 21         |
| 7            | 25        | 25         |
| 8            | 20        | 19         |
"""

import matplotlib.pyplot as plt
import numpy as np
# Declare a tabela como numpy
dados = np.array([
    [22, 20],
    [24, 23],
    [19, 18],
    [26, 25],
    [21, 22],
    [23, 21],
    [25, 25],
    [20, 19]
])
print(dados)

"""##### 1.1 - Quais são as hipóteses do Teste dos Sinais?

**Resposta:** H0 - As amostras não indicam diferença na frequência respiratória
H1 - As amostras indicam diferença na frequeência respiratória

##### 1.2 - Identifique diferenças positivas, negativas e empates
"""

diferencas = dados[:, 1] - dados[:, 0] # depois - antes

positivas = np.sum(diferencas > 0)
negativas = np.sum(diferencas < 0)
empates   = np.sum(diferencas == 0)

print(f"Positivas: {positivas}")
print(f"Negativas: {negativas}")
print(f"Empates:   {empates}")

"""##### 1.3 - Gere um gráfico de barras mostrando as diferenças"""

plt.bar(["Positivas", "Negativas", "Empates"], [positivas, negativas, empates])
plt.ylabel("Quantidade")
plt.title("Diferenças no Teste dos Sinais")
plt.show()

"""##### 1.4 - Calcule o p-valor"""

from scipy.stats import binom

n = positivas + negativas
k = negativas

p = binom.cdf(positivas, n, 0.5)

print(p)

"""##### 1.5 - Conclusão

**Resposta:** Não Rejeitamos H0 - Não há evidência suficiente de que o exercício reduz a frequência respiratória. A uma relevância de 6,25%
"""