# -*- coding: utf-8 -*-
"""ATV_13_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRaja8-FJ0nqmKIPl7zXWsag7SYskzjC

## Nome:Pedro Henrique Ribeiro Dias
## Matricula: 529
-----

# ATIVIDADE 13 — Testes de Hipóteses

**Objetivo:** Aplicar e interpretar testes de hipóteses para tomada de decisão com base em dados estatísticos.

---

## Resumo Teórico

Os testes de hipótese são procedimentos estatísticos usados para avaliar afirmações sobre uma população com base em dados de uma amostra. Primeiro, formulam-se duas hipóteses: a hipótese nula (H₀), que representa a suposição inicial, e a hipótese alternativa (H₁), que representa uma possível diferença ou efeito. Utiliza-se a curva normal e fórmulas de probabilidade para calcular a chance de observar os resultados obtidos. Com base nesse cálculo, decide-se aceitar ou rejeitar H₀, considerando o nível de significância (α) e o valor-p, garantindo assim decisões fundamentadas em evidências estatísticas.

---

## Exemplo Ilustrativo

Suponha que um estudo em determinada região mostra que a ingestão diária média de calórias em adultos é de 2400Kcal. Considere que em um grupo de 25 adultos desta população apresentou um consumo médio de 3000Kcal, com um desvio padrão populacional de 1250Kcal. Para testar se o consumo calórico deste grupo é diferente do padrão de consumoo da população, pode ser efetivado o teste da Normal para médias, como mostrado a seguir

## Dados importantes e suas devidas análises

- Média populacional -> μ = 2400Kcal
- Amostra = 25
- x = 3000
- Desvio Populacional  = 1250Kcal

– Média populacional (μ): é a média verdadeira da população inteira, ou seja, o valor esperado se medíssemos todos os indivíduos (no exemplo, 2400 Kcal).

– Amostra: é um pequeno grupo retirado da população para representar o todo (no exemplo, 25 adultos).

– Média amostral (x̄): é a média calculada com os dados da amostra (no exemplo, 3000 Kcal).

– Desvio padrão populacional (σ): mede quanto os valores da população variam em torno da média, indicando o grau de dispersão (no exemplo, 1250 Kcal).

---

## Passo 1

![image.png](attachment:image.png)

H₀ (hipótese nula): a média da amostra é igual à média populacional (x̄ = μ).
→ Ou seja, não há diferença entre o grupo e a população.

H₁ (hipótese alternativa): a média da amostra é diferente da média populacional (x̄ ≠ μ).
→ Ou seja, há diferença entre o grupo e a população.

---

## Passo 2

## Cálculo de Z, onde EP é o Erro Padrão da Média.

O EP ajuda a avaliar a confiabilidade da média amostral calculada.

## Fórmulas Imporantes!

![image.png](attachment:image.png)

Z = 3000 - 2400 / 250 = 2,4

![image.png](attachment:image.png)

EP = 1250 / √25 -> 250

---

## Passo 3

## Determinação do parametro p.

![image-2.png](attachment:image-2.png)

O valor da aréa hachurada, é o valor que queremos encontrar!


Aí fazemos os seguintes passos:
- Calculamos o valor da área de -∞ até 2,4. Chamaremos isso de A1.

A1 = 1 - (valor de pertinência de 2,4) -> 1 - 0,9918 = 0,0082

Importante: Para achar o valor de pertinência, basta olhar a tabela de distribuição de probabilidade.

- Agora calculamos o valor de p:

p = 2 x (1 - 0,9918) = 0.0164 = 1,64%

---

## Passo 4

## Tomada de Decisão.

- Para a tomada de decisão, olharemos na tabela abaixo, o nível se significância de p, e a partir disso, faremos a nossa decisão de aceitar ou rejeitar H0.

![image.png](attachment:image.png)

No nosso caso, o H0 será rejeitado, pois o p é igual a 1,64, ou seja, está entre 1% e 5%, com isso, há maior certeza para rejeitar H0.

---

## Passo 5

## Conclusão.

- Baseado no experimento que foi realizado, devemos fazer a conclusão do que foi obtido!

No nosso caso, a conclusão ideal seria: "Concluí-se que o consumo da amostra pode ser considerado diferente do da população, a um nível de significância de 1,64%".

---

## Questão1

Suponha que um estudo mostra que a média de horas de sono de adultos em uma cidade é de 7 horas por noite. Um grupo de 36 adultos dessa população apresentou uma média de 6 horas de sono, com um desvio padrão populacional de 1,8 hora. Para verificar se esse grupo dorme de forma diferente da média da população, pode-se aplicar o teste da Normal para médias.

- Faça os cálculos e chegue à conclusão do resultado obtido.

---
"""

import math
import scipy.stats as st

# Dados do problema:
# média populacional, média amostral, desvio padrão populacional e tamanho da amostra
mu = 7
x = 6
desvioP = 1.8
n = 36

# Passo 1 e 2 - Calcular o valor de Z
EP = desvioP / (n ** 0.5)
Z = (x - mu) / EP

# Passo 3 - Determinar o valor de p
p = 2 * (1 - st.norm.cdf(abs(Z)))

# Passo 4 - Tomada de decisão
print(f"Valor de p = {p:.4f} = {p*100:.2f}%. Valor é menor do que 1%, portanto certeza máxima para reijeitar h0")

# Passo 5 - Conclusão
print(f"Conclusão: O grupo apresenta uma média de horas de sono significativamente diferente da população, com um nível de significancia de {p*100:.2f}%")

"""## Parte Teórica

Responda as perguntas abaixo, utilizando suas próprias palavras!

-  Explique o que é Inferência Estatística, e fale quais são as informações coletadas pelo estatístico para realizar os cálculos.

-  Explique a diferença entre População e Amostra.

-  O que é Hipótese? E explique o que é o teste de hipótese?

-  O que quer dizer, quando falamos que H0 foi rejeitado?

**Respostas:**

1 - Inferência Estatística É o ato de usar dados de uma amostra para tirar conclusões sobre a população toda

O estatístico coleta informações como: Média dos dados, Desvio padrão, Tamanho da amostra e frequências. Usando elas para estimar parâmetros e testar hipóteses.

2 - População: é o conjunto total de indivíduos a serem estudados

Amostra: é um pequeno grupo retirado da população, representando o todo na análise.

3 - Hipótese: é uma suposição / afirmação sobre um parâmetro da população

Teste de hipótese: é um procedimento estatístico usado para verificar se essa afirmação é provável ou não, tendo como base os dados da amostra

4 -Significa que os dados da amostra mostram uma diferença significativa em relação ao que foi afirmado pela hipótese H₀, o que significa que pode-se dizer que o resultado da amostra não é igual ao esperado na população.
"""