# -*- coding: utf-8 -*-
"""ATV9_Pedro_Henrique_Ribeiro_Dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOcIcBfCwhwzGb9nM3GDOaThMKEBzS8V

## Nome: Pedro Henrique Ribeiro Dias
## Mátricula: 529
---

# Atividade 9 - Ajustes Não Lineares

## Objetivo da Atividade
Desenvolver a capacidade de ajustar dados experimentais a uma função exponencial e interpretar os parâmetros do modelo obtido.

## Contexto
Os dados a seguir representam o crescimento do número de seguidores de um influenciador em uma rede social após 𝑥 semanas:

| x (semanas) | 0 | 1 | 2 | 3  | 4  | 5  | 6  | 7  |
| ----- | - | - | - | -- | -- | -- | -- | -- |
| y     | 1 | 2 | 8 | 20 | 42 | 80 |178 |400 |

Encontre um modelo exponencial do tipo: $ y = a \times e^{bx} $

```
Dica:
A função `curve_fit()` do módulo scipy.optimize é usada para ajustar dados experimentais a um modelo matemático definido pelo usuário.

Ela recebe como entrada:
  - a função modelo (que descreve a relação esperada entre x e y, com parâmetros desconhecidos),
  - os valores medidos de x,
  - os valores medidos de y
```
"""

import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

"""1) Declare a função modelo"""

# Modelo exponencial
def modelo(x, a, b):
    return a * np.exp(b * x)

"""2) Declare os valores da tabela *(np.array)*"""

x = np.array([1, 2, 3, 4, 5, 6, 7])  # semanas
y = np.array([120, 155, 210, 290, 400, 560, 780])  # seguidores

"""3) Ajuste com `curve_fit()`"""

param, _ = curve_fit(modelo, x, y)

"""4) Exiba os parametros ajustados no modelo"""

a, b = param
print(f"Parâmetros ajustados: a = {a:.4f}, b = {b:.4f}")

"""5) Plote no Gráfico os pontos medidos e a reta ajustada"""

x_fit = np.linspace(min(x), max(x), 100)
y_fit = modelo(x_fit, a, b)

plt.plot(x_fit, y_fit, 'r-', label='Ajuste')
plt.scatter(x, y, label='Dados')
plt.legend()
plt.show()

"""6) Qual seria a previsão do modelo para o número de seguidores após 8 semanas?

*(Plote em um gráfico a curva ajustada junto com os dados reais e destaque o valor previsto).*
"""

x_prev = 8
y_prev = modelo(x_prev, a, b)
print(f"Previsão após {x_prev} semanas: {y_prev:.2f}")

plt.plot(x_fit, y_fit, 'r-', label='Ajuste')
plt.scatter(x, y, label='Dados')
plt.scatter(x_prev, y_prev, color='green', label='Previsão')
plt.legend()
plt.show()

"""7) O que significa o valor de 𝑏 em relação ao crescimento do número de seguidores?

**Resposta:** O valor de b indica a taxa de crescimento do número de seguidores.
Se b > 0, os seguidores aumentam de forma exponencial
se b < 0, o número de seguidores diminui com o tempo

8) O modelo ajustado representa bem os dados? Como podemos verificar isso visualmente no gráfico?

**Resposta:** O modelo representa bem os dados quando a curva ajustada fica próxima dos pontos reais no gráfico.
Visualmente, isso é verificado se a linha vermelha (que é o  modelo) segue o mesmo formato e tendência dos pontos azuis (dados reais obtidos).
"""